version: '3.1' 

services:
  oracle:
    container_name: oracle10g 
    image: oracle10g
    restart: always
    privileged: true
    ports:
      - "1521:1521"
    volumes:
      - /root/app/oracle/data/ora_data/mydata:/home/oracle/app/oracle/oradata/mydata
