version: '3.1'

services:
  nexus2:
    container_name: nexus2
    image: 172.16.178.61:5180/cmal/sonatype/nexus:2.14.8
    restart: always
    ports:
     - 9080:8081
    volumes:
     - ./nexus-data:/nexus-data
    