version: '3.1'

services:
  teamcity-server:
  
    container_name: teamcity-server
    image: 172.16.178.61:5180/cmal/jetbrains/teamcity-server:2023.05.1
    ports:
      - "8111:8111"
    volumes:
      - ./logs:/opt/teamcity/logs
      - ./data:/data/teamcity_server/datadir
      - ./jar:/data/teamcity_server/datadir/lib/jdbc

  teamcity-agent:
    container_name: teamcity-agent
    image: 172.16.178.61:5180/cmal/jetbrains/teamcity-agent:2023.05.1
    depends_on:
      - teamcity-server
    environment:
      - privileged=true
      - SERVER_URL=http://teamcity-server:8111
      - AGENT_NAME=teamcity-agent